### ISSUE TITLE
Getting "rejecting request with JWT token signed with untrusted key" when trying to compile tasks

### ISSUE THREAD

**Issue by latentflip** [auth0/webtaskify#3]
Not sure what I'm doing wrong, or if it's a bug, but here's what I'm trying:

```
npm install -g webtaskify
webtaskify login
# provide name, and token from https://webtask.io/token
echo "return function (data, cb) { cb(null, 'Hello'); }" > test.js
mkdir output
webtaskify create -f *.js -o output
```

I get this error:

```
There was an error creating your proxy files
403 - [object Object]
```

Which by doing webtaskify logs looks like is caused by:

```
New log entry:
code:    403
message: rejecting request with JWT token signed with untrusted key
```

Dunno if it's relevant, but I wasn't sure what to use for the token/tenant name in the login command. Tried my github username (which I used to login to webtasks.io; the longer form of it as shown in the example on /tokens; and just a made up name) all seem to have the same result.

**Comment by mgonto** [comment]
Hey there,

You're right. It's not really clear what information you have to put when Logging in with Webtaskify.

You have to go to the [token page](https://webtask.io/token).

In there, you'll find the token (which need to be set as the Token when logging in) and then, in the example of using that token, you'll see that after the `run` in the URL there's a name. That's your tenant (account) name:

![image](http://d.pr/i/1ecb1+)

Let me know if this helps.

We'll work on improving our docs to show you clearly your account name and token which need to be used with Webtaskify.

Thanks!

**Comment by latentflip** [comment]
@mgonto hmm, I tried that, and I still get the same error.

```
❯ cat ~/.webtaskify.cfg
{
  "tenantName": "wt-phil-latentflip_com-0",
  "tenantToken": "ey..."
}
```
